package com.uniquemovement.util;

import com.uniquemovement.UniqueMovementMod;
import com.uniquemovement.entity.aventador.EntityAventadorBlue;
import com.uniquemovement.entity.aventador.EntityAventadorGreen;
import com.uniquemovement.entity.aventador.EntityAventadorOrange;
import com.uniquemovement.entity.aventador.EntityAventadorPink;
import com.uniquemovement.entity.aventador.EntityAventadorPurple;
import com.uniquemovement.entity.aventador.EntityAventadorRed;
import com.uniquemovement.entity.aventador.EntityAventadorWhite;
import com.uniquemovement.entity.aventador.EntityAventadorYellow;
import com.uniquemovement.entity.bmx.EntityBMXBlue;
import com.uniquemovement.entity.bmx.EntityBMXGreen;
import com.uniquemovement.entity.bmx.EntityBMXOrange;
import com.uniquemovement.entity.bmx.EntityBMXPink;
import com.uniquemovement.entity.bmx.EntityBMXPurple;
import com.uniquemovement.entity.bmx.EntityBMXRed;
import com.uniquemovement.entity.bmx.EntityBMXWhite;
import com.uniquemovement.entity.bmx.EntityBMXYellow;
import com.uniquemovement.entity.cargoboat.EntityCargoBoat;
import com.uniquemovement.entity.hoverboard.EntityHoverboardBlue;
import com.uniquemovement.entity.hoverboard.EntityHoverboardGreen;
import com.uniquemovement.entity.hoverboard.EntityHoverboardMcFly;
import com.uniquemovement.entity.hoverboard.EntityHoverboardOrange;
import com.uniquemovement.entity.hoverboard.EntityHoverboardPink;
import com.uniquemovement.entity.hoverboard.EntityHoverboardPopularMMO;
import com.uniquemovement.entity.hoverboard.EntityHoverboardPurple;
import com.uniquemovement.entity.hoverboard.EntityHoverboardRed;
import com.uniquemovement.entity.hoverboard.EntityHoverboardSuperGirlyGamer;
import com.uniquemovement.entity.hoverboard.EntityHoverboardWhite;
import com.uniquemovement.entity.hoverboard.EntityHoverboardYellow;
import com.uniquemovement.entity.hovercraft.EntityHovercraftBlue;
import com.uniquemovement.entity.hovercraft.EntityHovercraftGreen;
import com.uniquemovement.entity.hovercraft.EntityHovercraftOrange;
import com.uniquemovement.entity.hovercraft.EntityHovercraftPink;
import com.uniquemovement.entity.hovercraft.EntityHovercraftPurple;
import com.uniquemovement.entity.hovercraft.EntityHovercraftRed;
import com.uniquemovement.entity.hovercraft.EntityHovercraftWhite;
import com.uniquemovement.entity.hovercraft.EntityHovercraftYellow;
import com.uniquemovement.entity.segway.EntitySegwayBlue;
import com.uniquemovement.entity.segway.EntitySegwayGreen;
import com.uniquemovement.entity.segway.EntitySegwayOrange;
import com.uniquemovement.entity.segway.EntitySegwayPink;
import com.uniquemovement.entity.segway.EntitySegwayPurple;
import com.uniquemovement.entity.segway.EntitySegwayRed;
import com.uniquemovement.entity.segway.EntitySegwayWhite;
import com.uniquemovement.entity.segway.EntitySegwayYellow;
import com.uniquemovement.entity.swegway.EntitySwegwayBlue;
import com.uniquemovement.entity.swegway.EntitySwegwayGreen;
import com.uniquemovement.entity.swegway.EntitySwegwayOrange;
import com.uniquemovement.entity.swegway.EntitySwegwayPink;
import com.uniquemovement.entity.swegway.EntitySwegwayPurple;
import com.uniquemovement.entity.swegway.EntitySwegwayRed;
import com.uniquemovement.entity.swegway.EntitySwegwayWhite;
import com.uniquemovement.entity.swegway.EntitySwegwayYellow;
import com.uniquemovement.entity.tardis.EntityTardis;
import com.uniquemovement.entity.unicycle.EntityUnicycleBlue;
import com.uniquemovement.entity.unicycle.EntityUnicycleGreen;
import com.uniquemovement.entity.unicycle.EntityUnicycleOrange;
import com.uniquemovement.entity.unicycle.EntityUnicyclePink;
import com.uniquemovement.entity.unicycle.EntityUnicyclePurple;
import com.uniquemovement.entity.unicycle.EntityUnicycleRed;
import com.uniquemovement.entity.unicycle.EntityUnicycleWhite;
import com.uniquemovement.entity.unicycle.EntityUnicycleYellow;
import com.uniquemovement.items.MovementItems;

import net.minecraft.block.Block;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.FurnaceRecipes;
import net.minecraftforge.fml.common.registry.EntityRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class UniqueEntitiesRegister {
	public static void loadEntities() {
		int entityID;
    	entityID = EntityRegistry.findGlobalUniqueEntityId();

    	EntityRegistry.registerModEntity(EntitySegwayWhite.class, "segway_white", 394, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySegwayBlue.class, "segway_blue", 395, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySegwayGreen.class, "segway_green", 396, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySegwayPurple.class, "segway_purple", 397, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySegwayPink.class, "segway_pink", 398, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySegwayRed.class, "segway_red", 399, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySegwayOrange.class, "segway_orange", 400, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySegwayYellow.class, "segway_yellow", 401, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySwegwayWhite.class, "swegway_white", 402, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySwegwayBlue.class, "swegway_blue", 403, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySwegwayGreen.class, "swegway_green", 404, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySwegwayPurple.class, "swegway_purple", 405, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySwegwayPink.class, "swegway_pink", 406, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySwegwayRed.class, "swegway_red", 407, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySwegwayOrange.class, "swegway_orange", 408, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntitySwegwayYellow.class, "swegway_yellow", 409, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardMcFly.class, "hoverboard_mcfly", 410, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardWhite.class, "hoverboard_white", 411, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardBlue.class, "hoverboard_blue", 412, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardGreen.class, "hoverboard_green", 413, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardPurple.class, "hoverboard_purple", 414, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardPink.class, "hoverboard_pink", 415, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardRed.class, "hoverboard_red", 416, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardOrange.class, "hoverboard_orange", 417, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardYellow.class, "hoverboard_yellow", 418, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityUnicycleWhite.class, "unicycle_white", 419, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityUnicycleBlue.class, "unicycle_blue", 420, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityUnicycleGreen.class, "unicycle_green", 421, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityUnicyclePurple.class, "unicycle_purple", 422, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityUnicyclePink.class, "unicycle_pink", 423, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityUnicycleRed.class, "unicycle_red", 424, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityUnicycleOrange.class, "unicycle_orange", 425, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityUnicycleYellow.class, "unicycle_yellow", 426, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityTardis.class, "tardis", 427, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityBMXWhite.class, "bmx_white", 428, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityBMXBlue.class, "bmx_blue", 429, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityBMXGreen.class, "bmx_green", 430, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityBMXPurple.class, "bmx_purple", 431, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityBMXPink.class, "bmx_pink", 432, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityBMXRed.class, "bmx_red", 433, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityBMXOrange.class, "bmx_orange", 434, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityBMXYellow.class, "bmx_yellow", 435, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityCargoBoat.class, "cargo_boat", 436, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityAventadorWhite.class, "aventador_white", 437, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityAventadorBlue.class, "aventador_blue", 438, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityAventadorGreen.class, "aventador_green", 439, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityAventadorPurple.class, "aventador_purple", 440, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityAventadorPink.class, "aventador_pink", 441, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityAventadorRed.class, "aventador_red", 442, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityAventadorOrange.class, "aventador_orange", 443, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityAventadorYellow.class, "aventador_yellow", 444, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHovercraftWhite.class, "hovercraft_white", 445, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHovercraftBlue.class, "hovercraft_blue", 446, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHovercraftGreen.class, "hovercraft_green", 447, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHovercraftPurple.class, "hovercraft_purple", 448, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHovercraftPink.class, "hovercraft_pink", 449, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHovercraftRed.class, "hovercraft_red", 450, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHovercraftOrange.class, "hovercraft_orange", 451, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHovercraftYellow.class, "hovercraft_yellow", 452, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardSuperGirlyGamer.class, "hoverboard_supergirlygamer", 453, UniqueMovementMod.instance, 80, 3, true);
    	EntityRegistry.registerModEntity(EntityHoverboardPopularMMO.class, "hoverboard_popularmmo", 454, UniqueMovementMod.instance, 80, 3, true);
    	
	}
}