package com.uniquemovement;

import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.SocketTimeoutException;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Random;

import javax.imageio.ImageIO;
import javax.swing.text.JTextComponent.KeyBinding;

import com.uniquemovement.events.DonatorEventHandler;
import com.uniquemovement.gui.CargoBoatGuiHandler;
import com.uniquemovement.gui.TileEntityCargoBoat;
import com.uniquemovement.items.MovementItems;
import com.uniquemovement.player.PlayerOverrideSwegway;
import com.uniquemovement.proxy.CommonProxy;
import com.uniquemovement.util.BaseModChecker;
import com.uniquemovement.util.Recipe;
import com.uniquemovement.util.Reference;
import com.uniquemovement.util.MovementTab;
import com.uniquemovement.util.UniqueEntitiesRegister;

import net.java.games.input.Keyboard;
import net.minecraft.client.Minecraft;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.world.World;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.InputEvent.KeyInputEvent;
import net.minecraftforge.fml.common.network.NetworkRegistry;
import net.minecraftforge.fml.common.registry.EntityRegistry;
import net.minecraftforge.fml.common.registry.GameRegistry;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.VERSION)
public class UniqueMovementMod {
//GITHUB TEST
	@Instance(Reference.MOD_ID)
	public static UniqueMovementMod instance;
	
	@SidedProxy(clientSide = Reference.CLIENT_PROXY_CLASS, serverSide = Reference.COMMON_PROXY_CLASS)
	
	public static CommonProxy proxy;

	public static double SegwaySpeed = 0.15D;
	public static double HoverboardSpeed = 0.17D;
	public static double SwegwaySpeed = 0.13D;
	public static double UnicycleSpeed = 0.10D;
	public static double TardisSpeed = 0.3D;
	public static double BMXSpeed = 0.19D;
	public static double CargoBoatSpeed = 0.3D;
	public static double HovercraftSpeed = 0.3D;
	public static double AventadorSpeed = 0.32D;
	
	public static int CARGO_BOAT_GUI_ID = 0;
	
	public static CreativeTabs MovementTab = new MovementTab("tabMovement");

	public static String ASSET_PREFIX = "uniquemovement";
    public static String TEXTURE_PREFIX = UniqueMovementMod.ASSET_PREFIX + ":";
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		FMLCommonHandler.instance().bus().register(new DonatorEventHandler());
			
		MovementItems.init();
		MovementItems.register();
		Recipe.loadRecipes();
		BaseModChecker.checkForBaseMod();
		int entityID;
    	entityID = EntityRegistry.findGlobalUniqueEntityId();
    	UniqueEntitiesRegister.loadEntities();
    	FMLCommonHandler.instance().bus().register(new CargoBoatGuiHandler());
    	GameRegistry.registerTileEntity(TileEntityCargoBoat.class, "containerCargoBoat");
    
    	ArrayList<String> author = new ArrayList<String>();
		author.add(Reference.MOD_AUTHOR);
		event.getModMetadata().autogenerated = false;
		event.getModMetadata().description = Reference.MOD_DESCRIPTION;
		event.getModMetadata().modId = Reference.MOD_ID;
		event.getModMetadata().url = Reference.MOD_URL;
		event.getModMetadata().name = Reference.MOD_NAME;
		event.getModMetadata().version = Reference.VERSION;
		event.getModMetadata().logoFile = Reference.MOD_LOGO_FILE;
		event.getModMetadata().authorList = author;
		
		
       }

	@EventHandler
	public void Init(FMLInitializationEvent event)
	{	
		proxy.register();
		proxy.registerRenders();
		this.proxy.init(event);
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		//Nothing here for now.
	}
	 public static String readPage(URL url) throws Exception {
	        try {
	            String current;
	            URLConnection urlConnection = url.openConnection();
	            urlConnection.setConnectTimeout(1000);
	            HttpURLConnection connection = null;
	            if (!(urlConnection instanceof HttpURLConnection)) {
	                
	                return null;
	            }
	            connection = (HttpURLConnection)urlConnection;
	            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
	            String urlString = "";
	            while ((current = in.readLine()) != null) {
	                urlString = urlString + current;
	            }
	            return urlString;
	        }
	        catch (SocketTimeoutException e) {
	            return "";
	        }
	    }

}